# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Zipline < Formula
  desc ""
  homepage ""
  version "0.2.1"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/bilal-bhatti/zipline/releases/download/v0.2.1/zipline_0.2.1_Darwin_x86_64.tar.gz"
    sha256 "9b5a5a76c616687228ed90a908ffb2ee9c816d63d1822bcf480490af8d7f3a18"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/bilal-bhatti/zipline/releases/download/v0.2.1/zipline_0.2.1_Darwin_arm64.tar.gz"
    sha256 "31a841622f4539a7c48711d5cfa5ba8e554872fa4ed225decb4296fdb63e7217"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/bilal-bhatti/zipline/releases/download/v0.2.1/zipline_0.2.1_Linux_x86_64.tar.gz"
    sha256 "5498f8b84425b1a528cc1f7bb4b167875799cb4bb4ce6acefc5607221808d417"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/bilal-bhatti/zipline/releases/download/v0.2.1/zipline_0.2.1_Linux_arm64.tar.gz"
    sha256 "ae32a1cbe3a1c19b7f4c813957602927832676d05842b031485f762f35cda9b5"
  end

  def install
    bin.install "zipline"
  end
end
